package io.github.thefishlive.http;

public enum HttpStatusCode {

	CONTINUE(100),
	SWITCHING_PROTOCOLS(101),
	
	OK(200),
	CREATED(201),
	ACCEPTED(202),
	NO_CONTENT(204),
	RESET_CONTENT(205),
	PARTIAL_COTNENT(206),
	
	MULTIPLE_CHOICES(300),
	MOVED_PERMANENTLY(301),
	FOUND(302),
	SEE_OTHER(303),
	NO_MODIFIED(304),
	USE_PROXY(305),
	SWITCH_PROXY(306),
	TEMPORARY_REDIRECT(307),
	
	BAD_REQUEST(400),
	UNAUTHOIRIZED(401),
	FORBIDDEN(403),
	NOT_FOUND(404),
	METHOD_NOT_ALLOWED(405),
	NOT_ACCEPTABLE(406),
	PROXY_AUTHENTICATION_REQUIRED(407),
	REQUEST_TIMEOUT(408),
	CONFILICT(409),
	GONE(410),
	LENGTH_REQUIRED(411),
	PRECONDITION_FAILED(412),
	REQUEST_ENTITY_TOO_LARGE(413),
	REQUEST_URI_TOO_LONG(404),
	UNSUPPORTED_MEDIA_TYPE(415),
	REQUEST_RANGE_NOT_STISFIABLE(416),
	EXPECTATION_FAILED(417),
	IM_A_TEAPOT(418),
	AUTHENTICATION_TIMEOUT(419),
	ENHANCE_YOUR_CALM(420),
	UPGRADE_REQUIRED(426),
	PRECONDITION_REQUIRED(428),
	TOO_MANY_REQUESTS(429),
	REQUEST_HEADER_FIELDS_TOO_LARGE(431),
	
	SERVER_ERROR(500),
	NOT_IMPLEMENTED(501),
	BAD_GATEWAY(502),
	SERVICE_UNAVAIABLE(503),
	HTTP_VERSION_NOT_SUPPORTED(505),
	VARIANT_ALSO_NEGOTIATES(506), 
	
	UNKNOWN(-1),
	;
	
	private int code;

	private HttpStatusCode(int code) {
		this.code = code;
	}
	
	public int getCode() {
		return this.code;
	}
	
	public static HttpStatusCode fromCode(int code) {
		for (HttpStatusCode value : values()) {
			if (value.getCode() == code) {
				return value;
			}
		}
		
		return UNKNOWN;
	}
}
